export const signUpFormUrl = 'https://forms.pingcap.com/f/hackathon-2022';
export const joinGroupFormUrl = 'https://pingcap.feishu.cn/share/base/shrcnaTxgdc234p8s9ri0xCXM9g';
export const RfcSubmitFormUrl = 'https://asktug.com/t/topic/903770';
export const RfcDescriptionZhUrl = 'https://asktug.com/t/topic/903770';
export const guideUrl = 'https://asktug.com/t/topic/903772';
export const joinGroupHelpUrl = 'https://asktug.com/t/topic/903781';
export const pptTemplateUrl =
  'https://docs.google.com/presentation/d/1OcIpL5MEZPPbjiSnbpnqHPwoO1cE5nBBq2oyVllmQ_4/edit?usp=sharing';
export const askCompetitionUrl = 'https://asktug.com/c/Mutual-communication/Hackathon';
export const scoreRule = 'https://asktug.com/t/topic/933123';
export const liveUrl = 'https://live.bilibili.com/4630260';
export const ideaUrl = 'https://asktug.com/t/topic/933124';
export const studyResourceUrl = 'https://asktug.com/t/topic/903772';
