module.exports = {
  content: [
    {
      id: 10,
      name: '生态应用',
      slug: 'ecological-application',
      description: '生态应用',
      posts: 0,
    },
    {
      id: 18,
      name: '最佳实践',
      slug: 'best-practices',
      description: '最佳实践',
      posts: 0,
    },
    {
      id: 17,
      name: '运维实战',
      slug: 'operation-and-maintenance',
      description: '运维实战',
      posts: 0,
    },
    {
      id: 16,
      name: '原理解读',
      slug: 'principle-interpretation',
      description: '原理解读',
      posts: 0,
    },
    {
      id: 15,
      name: '用户实践',
      slug: 'user-practice',
      description: '用户实践',
      posts: 0,
    },
    {
      id: 14,
      name: '选型',
      slug: 'selection',
      description: '选型',
      posts: 0,
    },
    {
      id: 13,
      name: '性能测试',
      slug: 'performance-testing',
      description: '性能测试',
      posts: 0,
    },
    {
      id: 12,
      name: '行业场景',
      slug: 'industry-scene',
      description: '行业场景',
      posts: 0,
    },
    {
      id: 11,
      name: '新版本',
      slug: 'new-version',
      description: '新版本',
      posts: 0,
    },
    {
      id: 1,
      name: '安装部署',
      slug: 'installation-and-deployment',
      description: '安装部署',
      posts: 0,
    },
    {
      id: 9,
      name: '社区动态',
      slug: 'community-dynamics',
      description: '社区动态',
      posts: 0,
    },
    {
      id: 8,
      name: '迁移',
      slug: 'migrate',
      description: '迁移',
      posts: 0,
    },
    {
      id: 7,
      name: '经验教程',
      slug: 'experience-tutorial',
      description: '经验教程',
      posts: 0,
    },
    {
      id: 6,
      name: '监控',
      slug: 'monitor',
      description: '监控',
      posts: 0,
    },
    {
      id: 5,
      name: '技术选项',
      slug: 'technical-options',
      description: '技术选项',
      posts: 0,
    },
    {
      id: 4,
      name: '故障案例',
      slug: 'failure-case',
      description: '故障案例',
      posts: 0,
    },
    {
      id: 3,
      name: '调优',
      slug: 'tuning',
      description: '调优',
      posts: 0,
    },
    {
      id: 2,
      name: '测评',
      slug: 'evaluation',
      description: '测评',
      posts: 0,
    },
  ],
};
