module.exports = {
  posts: [
    {
      creatorId: 0,
      createdAt: '2021-11-10T07:49:15.021Z',
      modifierId: 0,
      lastModifiedAt: '2021-11-10T07:49:15.021Z',
      deletedAt: '2021-11-10T07:49:15.021Z',
      id: 0,
      version: 0,
      title: 'string',
      content: 'string',
      status: 'DRAFT',
      origin: 'ORIGINAL',
      sourceURL: 'string',
      author: {
        creatorId: 0,
        createdAt: '2021-11-10T07:49:15.021Z',
        modifierId: 0,
        lastModifiedAt: '2021-11-10T07:49:15.021Z',
        deletedAt: '2021-11-10T07:49:15.021Z',
        id: 0,
        username: 'string',
        name: 'string',
        introduction: 'string',
        avatarURL: 'string',
        openid: 'string',
        roles: [
          {
            id: 0,
            name: 'string',
            displayName: 'string',
            authorities: [
              {
                id: 0,
                name: 'string',
                displayName: 'string',
                authority: 'string',
              },
            ],
          },
        ],
        authorities: [
          {
            id: 0,
            name: 'string',
            displayName: 'string',
            authority: 'string',
          },
        ],
      },
      category: {
        creatorId: 0,
        createdAt: '2021-11-10T07:49:15.021Z',
        modifierId: 0,
        lastModifiedAt: '2021-11-10T07:49:15.021Z',
        deletedAt: '2021-11-10T07:49:15.021Z',
        id: 0,
        name: 'string',
        slug: 'string',
        weight: 0,
        description: 'string',
      },
      tags: [
        {
          creatorId: 0,
          createdAt: '2021-11-10T07:49:15.021Z',
          modifierId: 0,
          lastModifiedAt: '2021-11-10T07:49:15.021Z',
          deletedAt: '2021-11-10T07:49:15.021Z',
          id: 0,
          name: 'string',
          slug: 'string',
          weight: 0,
          description: 'string',
        },
      ],
      comments: 0,
      recommended: true,
      recommender: {
        creatorId: 0,
        createdAt: '2021-11-10T07:49:15.021Z',
        modifierId: 0,
        lastModifiedAt: '2021-11-10T07:49:15.021Z',
        deletedAt: '2021-11-10T07:49:15.021Z',
        id: 0,
        username: 'string',
        name: 'string',
        introduction: 'string',
        avatarURL: 'string',
        openid: 'string',
        roles: [
          {
            id: 0,
            name: 'string',
            displayName: 'string',
            authorities: [
              {
                id: 0,
                name: 'string',
                displayName: 'string',
                authority: 'string',
              },
            ],
          },
        ],
        authorities: [
          {
            id: 0,
            name: 'string',
            displayName: 'string',
            authority: 'string',
          },
        ],
      },
      recommendAt: '2021-11-10T07:49:15.021Z',
      publisher: {
        creatorId: 0,
        createdAt: '2021-11-10T07:49:15.021Z',
        modifierId: 0,
        lastModifiedAt: '2021-11-10T07:49:15.021Z',
        deletedAt: '2021-11-10T07:49:15.021Z',
        id: 0,
        username: 'string',
        name: 'string',
        introduction: 'string',
        avatarURL: 'string',
        openid: 'string',
        roles: [
          {
            id: 0,
            name: 'string',
            displayName: 'string',
            authorities: [
              {
                id: 0,
                name: 'string',
                displayName: 'string',
                authority: 'string',
              },
            ],
          },
        ],
        authorities: [
          {
            id: 0,
            name: 'string',
            displayName: 'string',
            authority: 'string',
          },
        ],
      },
      publishedAt: '2021-11-10T07:49:15.021Z',
      public: true,
      likes: 0,
      shares: 0,
      favorites: 0,
      visits: 0,
    },
  ],
};
