module.exports = {
  content: [
    {
      id: 1,
      interfaceMethod: 'com.pingcap.community.blogserver.controller.PostController.createPost',
      requestMethod: 'POST',
      requestURL: '/blog/api/posts',
      requestParams: '{}',
      requestBody:
        '{"tags": [null], "title": "title", "origin": "REPOST", "content": "[{\\"type\\":\\"paragraph\\",\\"children\\":[{\\"text\\":\\"feawfewf\\"}]}]", "category": {"id": 1, "name": null, "slug": null, "weight": null, "createdAt": null, "creatorId": null, "deletedAt": null, "modifierId": null, "description": null, "lastModifiedAt": null}, "sourceURL": "fewafewffa", "coverImageURL": null}',
      creatorId: 2,
      createdAt: '2021-11-17T06:58:55.000+00:00',
    },
    {
      id: 2,
      interfaceMethod: 'com.pingcap.community.blogserver.controller.PostController.addPostComments',
      requestMethod: 'POST',
      requestURL: '/blog/api/posts/1/comments',
      requestParams: '{}',
      requestBody: '{"content": "测试", "replyCommentID": null}',
      creatorId: 2,
      createdAt: '2021-11-17T18:25:08.000+00:00',
    },
    {
      id: 3,
      interfaceMethod: 'com.pingcap.community.blogserver.controller.PostController.addPostComments',
      requestMethod: 'POST',
      requestURL: '/blog/api/posts/1/comments',
      requestParams: '{}',
      requestBody: '{"content": "测试", "replyCommentID": null}',
      creatorId: 2,
      createdAt: '2021-11-17T18:25:10.000+00:00',
    },
    {
      id: 4,
      interfaceMethod: 'com.pingcap.community.blogserver.controller.PostController.addPostComments',
      requestMethod: 'POST',
      requestURL: '/blog/api/posts/1/comments',
      requestParams: '{}',
      requestBody: '{"content": "测试", "replyCommentID": null}',
      creatorId: 2,
      createdAt: '2021-11-17T18:25:12.000+00:00',
    },
    {
      id: 5,
      interfaceMethod: 'com.pingcap.community.blogserver.controller.PostController.addPostComments',
      requestMethod: 'POST',
      requestURL: '/blog/api/posts/1/comments',
      requestParams: '{}',
      requestBody: '{"content": "fewafewf", "replyCommentID": null}',
      creatorId: 2,
      createdAt: '2021-11-17T19:28:15.000+00:00',
    },
    {
      id: 6,
      interfaceMethod: 'com.pingcap.community.blogserver.controller.PostController.addPostComments',
      requestMethod: 'POST',
      requestURL: '/blog/api/posts/1/comments',
      requestParams: '{}',
      requestBody: '{"content": "1", "replyCommentID": null}',
      creatorId: 2,
      createdAt: '2021-11-17T19:28:44.000+00:00',
    },
    {
      id: 7,
      interfaceMethod: 'com.pingcap.community.blogserver.controller.PostController.addPostComments',
      requestMethod: 'POST',
      requestURL: '/blog/api/posts/1/comments',
      requestParams: '{}',
      requestBody: '{"content": "12", "replyCommentID": null}',
      creatorId: 2,
      createdAt: '2021-11-17T19:28:46.000+00:00',
    },
    {
      id: 8,
      interfaceMethod: 'com.pingcap.community.blogserver.controller.PostController.addPostComments',
      requestMethod: 'POST',
      requestURL: '/blog/api/posts/1/comments',
      requestParams: '{}',
      requestBody: '{"content": "12", "replyCommentID": null}',
      creatorId: 2,
      createdAt: '2021-11-17T19:28:48.000+00:00',
    },
    {
      id: 9,
      interfaceMethod: 'com.pingcap.community.blogserver.controller.PostController.addPostComments',
      requestMethod: 'POST',
      requestURL: '/blog/api/posts/1/comments',
      requestParams: '{}',
      requestBody: '{"content": "333", "replyCommentID": null}',
      creatorId: 2,
      createdAt: '2021-11-17T19:28:52.000+00:00',
    },
    {
      id: 10,
      interfaceMethod: 'com.pingcap.community.blogserver.controller.PostController.addPostComments',
      requestMethod: 'POST',
      requestURL: '/blog/api/posts/1/comments',
      requestParams: '{}',
      requestBody: '{"content": "4213", "replyCommentID": null}',
      creatorId: 2,
      createdAt: '2021-11-17T19:28:58.000+00:00',
    },
    {
      id: 11,
      interfaceMethod: 'com.pingcap.community.blogserver.controller.PostController.addPostComments',
      requestMethod: 'POST',
      requestURL: '/blog/api/posts/1/comments',
      requestParams: '{}',
      requestBody: '{"content": "42133333", "replyCommentID": null}',
      creatorId: 2,
      createdAt: '2021-11-17T19:29:00.000+00:00',
    },
    {
      id: 12,
      interfaceMethod: 'com.pingcap.community.blogserver.controller.PostController.addPostComments',
      requestMethod: 'POST',
      requestURL: '/blog/api/posts/1/comments',
      requestParams: '{}',
      requestBody: '{"content": "fewafwef", "replyCommentID": null}',
      creatorId: 2,
      createdAt: '2021-11-17T19:29:06.000+00:00',
    },
    {
      id: 13,
      interfaceMethod: 'com.pingcap.community.blogserver.controller.PostController.addPostComments',
      requestMethod: 'POST',
      requestURL: '/blog/api/posts/1/comments',
      requestParams: '{}',
      requestBody: '{"content": "fewafwef", "replyCommentID": null}',
      creatorId: 2,
      createdAt: '2021-11-17T19:29:07.000+00:00',
    },
    {
      id: 14,
      interfaceMethod: 'com.pingcap.community.blogserver.controller.PostController.createPost',
      requestMethod: 'POST',
      requestURL: '/blog/api/posts',
      requestParams: '{}',
      requestBody:
        '{"tags": [{"id": 2, "name": null, "slug": null, "weight": 10, "createdAt": null, "creatorId": null, "deletedAt": null, "modifierId": null, "description": null, "lastModifiedAt": null}, {"id": 4, "name": null, "slug": null, "weight": 10, "createdAt": null, "creatorId": null, "deletedAt": null, "modifierId": null, "description": null, "lastModifiedAt": null}, {"id": 6, "name": null, "slug": null, "weight": 10, "createdAt": null, "creatorId": null, "deletedAt": null, "modifierId": null, "description": null, "lastModifiedAt": null}], "title": "title", "origin": "REPOST", "content": "[{\\"type\\":\\"list\\",\\"children\\":[{\\"type\\":\\"listItem\\",\\"children\\":[{\\"type\\":\\"paragraph\\",\\"children\\":[{\\"text\\":\\"vgeawfwef\\"}]}]},{\\"type\\":\\"listItem\\",\\"children\\":[{\\"type\\":\\"paragraph\\",\\"children\\":[{\\"text\\":\\"fewafwef\\"}]}]}],\\"ordered\\":false},{\\"type\\":\\"paragraph\\",\\"children\\":[{\\"text\\":\\"geawfewfewfew\\"}]},{\\"type\\":\\"paragraph\\",\\"children\\":[{\\"text\\":\\"\\"}]}]", "category": {"id": 2, "name": null, "slug": null, "weight": null, "createdAt": null, "creatorId": null, "deletedAt": null, "modifierId": null, "description": null, "lastModifiedAt": null}, "sourceURL": "https://www.baidu.com", "coverImageURL": null}',
      creatorId: 2,
      createdAt: '2021-11-18T11:43:38.000+00:00',
    },
    {
      id: 15,
      interfaceMethod: 'com.pingcap.community.blogserver.controller.PostController.savePost',
      requestMethod: 'PUT',
      requestURL: '/blog/api/posts/2',
      requestParams: '{}',
      requestBody:
        '{"tags": [{"id": 6, "name": null, "slug": null, "weight": 10, "createdAt": null, "creatorId": null, "deletedAt": null, "modifierId": null, "description": null, "lastModifiedAt": null}, {"id": 4, "name": null, "slug": null, "weight": 10, "createdAt": null, "creatorId": null, "deletedAt": null, "modifierId": null, "description": null, "lastModifiedAt": null}, {"id": 2, "name": null, "slug": null, "weight": 10, "createdAt": null, "creatorId": null, "deletedAt": null, "modifierId": null, "description": null, "lastModifiedAt": null}], "title": "title", "origin": "REPOST", "content": "[{\\"type\\":\\"list\\",\\"children\\":[{\\"type\\":\\"listItem\\",\\"children\\":[{\\"type\\":\\"paragraph\\",\\"children\\":[{\\"text\\":\\"vgeawfwef\\"}]}]},{\\"type\\":\\"listItem\\",\\"children\\":[{\\"type\\":\\"paragraph\\",\\"children\\":[{\\"text\\":\\"fewafwef\\"}]}]}],\\"ordered\\":false},{\\"type\\":\\"paragraph\\",\\"children\\":[{\\"text\\":\\"geawfewfewfew\\"}]},{\\"type\\":\\"paragraph\\",\\"children\\":[{\\"text\\":\\"\\"}]}]", "category": {"id": 2, "name": null, "slug": null, "weight": null, "createdAt": null, "creatorId": null, "deletedAt": null, "modifierId": null, "description": null, "lastModifiedAt": null}, "sourceURL": "https://www.baidu.com", "coverImageURL": null}',
      creatorId: 2,
      createdAt: '2021-11-18T11:43:48.000+00:00',
    },
    {
      id: 16,
      interfaceMethod: 'com.pingcap.community.blogserver.controller.PostController.submitPost',
      requestMethod: 'PATCH',
      requestURL: '/blog/api/posts/2/submit',
      requestParams: '{}',
      requestBody: null,
      creatorId: 2,
      createdAt: '2021-11-18T11:43:48.000+00:00',
    },
    {
      id: 17,
      interfaceMethod: 'com.pingcap.community.blogserver.controller.PostController.rejectPost',
      requestMethod: 'PATCH',
      requestURL: '/blog/api/posts/2/reject',
      requestParams: '{}',
      requestBody: null,
      creatorId: 2,
      createdAt: '2021-11-18T11:43:51.000+00:00',
    },
    {
      id: 18,
      interfaceMethod: 'com.pingcap.community.blogserver.controller.PostController.savePost',
      requestMethod: 'PUT',
      requestURL: '/blog/api/posts/2',
      requestParams: '{}',
      requestBody:
        '{"tags": [{"id": 6, "name": null, "slug": null, "weight": 10, "createdAt": null, "creatorId": null, "deletedAt": null, "modifierId": null, "description": null, "lastModifiedAt": null}, {"id": 4, "name": null, "slug": null, "weight": 10, "createdAt": null, "creatorId": null, "deletedAt": null, "modifierId": null, "description": null, "lastModifiedAt": null}, {"id": 2, "name": null, "slug": null, "weight": 10, "createdAt": null, "creatorId": null, "deletedAt": null, "modifierId": null, "description": null, "lastModifiedAt": null}], "title": "title", "origin": "REPOST", "content": "[{\\"type\\":\\"list\\",\\"children\\":[{\\"type\\":\\"listItem\\",\\"children\\":[{\\"type\\":\\"paragraph\\",\\"children\\":[{\\"text\\":\\"vgeawfwef\\"}]}]},{\\"type\\":\\"listItem\\",\\"children\\":[{\\"type\\":\\"paragraph\\",\\"children\\":[{\\"text\\":\\"fewafwef\\"}]}]}],\\"ordered\\":false},{\\"type\\":\\"paragraph\\",\\"children\\":[{\\"text\\":\\"geawfewfewfew\\"}]},{\\"type\\":\\"paragraph\\",\\"children\\":[{\\"text\\":\\"\\"}]}]", "category": {"id": 2, "name": null, "slug": null, "weight": null, "createdAt": null, "creatorId": null, "deletedAt": null, "modifierId": null, "description": null, "lastModifiedAt": null}, "sourceURL": "https://www.baidu.com", "coverImageURL": null}',
      creatorId: 2,
      createdAt: '2021-11-18T11:43:55.000+00:00',
    },
    {
      id: 19,
      interfaceMethod: 'com.pingcap.community.blogserver.controller.PostController.savePost',
      requestMethod: 'PUT',
      requestURL: '/blog/api/posts/2',
      requestParams: '{}',
      requestBody:
        '{"tags": [{"id": 6, "name": null, "slug": null, "weight": 10, "createdAt": null, "creatorId": null, "deletedAt": null, "modifierId": null, "description": null, "lastModifiedAt": null}, {"id": 4, "name": null, "slug": null, "weight": 10, "createdAt": null, "creatorId": null, "deletedAt": null, "modifierId": null, "description": null, "lastModifiedAt": null}, {"id": 2, "name": null, "slug": null, "weight": 10, "createdAt": null, "creatorId": null, "deletedAt": null, "modifierId": null, "description": null, "lastModifiedAt": null}], "title": "title", "origin": "REPOST", "content": "[{\\"type\\":\\"list\\",\\"children\\":[{\\"type\\":\\"listItem\\",\\"children\\":[{\\"type\\":\\"paragraph\\",\\"children\\":[{\\"text\\":\\"vgeawfwef\\"}]}]},{\\"type\\":\\"listItem\\",\\"children\\":[{\\"type\\":\\"paragraph\\",\\"children\\":[{\\"text\\":\\"fewafwef\\"}]}]}],\\"ordered\\":false},{\\"type\\":\\"paragraph\\",\\"children\\":[{\\"text\\":\\"geawfewfewfew\\"}]},{\\"type\\":\\"paragraph\\",\\"children\\":[{\\"text\\":\\"\\"}]}]", "category": {"id": 2, "name": null, "slug": null, "weight": null, "createdAt": null, "creatorId": null, "deletedAt": null, "modifierId": null, "description": null, "lastModifiedAt": null}, "sourceURL": "https://www.baidu.com", "coverImageURL": null}',
      creatorId: 2,
      createdAt: '2021-11-18T11:44:09.000+00:00',
    },
    {
      id: 20,
      interfaceMethod: 'com.pingcap.community.blogserver.controller.PostController.addPostComments',
      requestMethod: 'POST',
      requestURL: '/blog/api/posts/2/comments',
      requestParams: '{}',
      requestBody: '{"content": "fewageawfe", "replyCommentID": null}',
      creatorId: 2,
      createdAt: '2021-11-18T11:44:28.000+00:00',
    },
  ],
};
